name: Hourly Weather ETL

on:
  schedule:
    - cron: '*/10 * * * *' #
  workflow_dispatch: # This allows the "Run Workflow" button to appear

permissions:
  contents: write # Crucial for allowing the bot to push the .db file back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL Script
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python main.py

      - name: Commit and Push .db file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.db
          git commit -m "Automated: Hourly weather update" || echo "No changes to commit"
          git push